version: '3.9'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: LoginDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env